name: build

on:
  push:
    branches:
      - 'main'  
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run compile
    - name: Copy frontend files
      run: npm run copy-web
    - name: Pack
      run: npm run pack
